Master
datil/link-dotnet pull request #8
Opened 2019-12-17 03:03 UTC by patorey3

Saludos, realicé cambios en la clase Factura,
y agregue funcionalidad para Liquidaciones en compra

2019-12-17 15:58 UTC, jplaza requested changes
Hola @patorey3 ! Muchísimas gracias por tu aporte ¿Podrías cambiar los nombres de las clases que se ven como truncados por el nombre completo?
Me refiero a los que terminan con la "C" como `FormaPagoLiquidacionC.cs` sería mejor si se llamase `FormaPagoLiquidacionCompra.cs` y así con todos los que terminan en "C"

Si tienes un ejemplo del uso de liquidaciones como este de Factura https://github.com/datil/link-dotnet/blob/master/EjemploCSharp/FacturaEjemplo.cs sería una buena adición también, pero si no lo tienes no hay problema.

2019-12-18 14:09 UTC, patorey3 commented
Hola @jplaza 
La próxima cambiaré los nombres de las clases.
Saludos.

2019-12-19 03:47 UTC, jplaza commented
> Hola @jplaza
> La próxima cambiaré los nombres de las clases.
> Saludos.

Aun no he juntado tus cambios con nuestro repositorio. Así que puedes subir más cambios en esa misma rama y hacer un push de tu rama y listo, se subirán los cambios aquí mismo en este mismo Pull Request

2019-12-21 20:58 UTC, patorey3 reviewed
Nombres de las clases No Truncados

2020-01-23 22:17 UTC, merged